[project] 
name = "telco-customer-segmentation-churn"
version = "1.0.0"
description = "A project for telco customer segmentation and churn prediction."
readme = "README.md"
authors = [
    { name = "reda-guemry", email = "guemryreda@gmail.com" }
]

requires-python = ">=3.14"

dependencies = [
    "imbalanced-learn>=0.14.2",
    "joblib>=1.6.0",
    "mlflow>=3.17.0",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]

